[versions]
android-compileSdk = "34"
android-minSdk = "21"
android-targetSdk = "34"
compose = "1.6.11"
log4k-demo = "1.0.0"
gradle-android = "8.5.2"
jacoco = "0.8.11"
java = "17"
kotlin = "2.0.10"
ktlint = "1.3.1"
mockk = "1.13.12"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.9.1"
kotlin-wrappers = "org.jetbrains.kotlin-wrappers:kotlin-node:20.14.10-pre.788"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.0"
kotlinx-io = "org.jetbrains.kotlinx:kotlinx-io-core:0.5.1"
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
slf4j-api = "org.slf4j:slf4j-api:1.7.36"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-android" }
android-library = { id = "com.android.library", version.ref = "gradle-android" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.8.3" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
