name: Main CI
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run Spotless
        run: ./gradlew spotlessCheck

  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log4k_build
          path: |
            .gradle
            build
            log4k/build
            log4k-slf4j/build

  publish:
    needs: build
    runs-on: macos-12
    if: github.ref == 'refs/heads/main'
    environment: Sonatype
    env:
      SONATYPE_GPG_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
      SONATYPE_GPG_KEY_PASSWORD: ${{ secrets.SONATYPE_GPG_KEY_PASSWORD }}
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: log4k_build
      - name: Publish to Sonatype (Maven Central)
        shell: bash
        run: |
          brew install gnupg
          ./scripts/secret decrypt --password ${SECRETS_KEY}
          ./scripts/publish
