name: Main CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive .gradle folder
        uses: actions/upload-artifact@v1
        with:
          name: .gradle
          path: .gradle
      - name: Archive build folder
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Archive log4k/build folder
        uses: actions/upload-artifact@v1
        with:
          name: log4k_build
          path: log4k/build

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
    steps:
      - uses: actions/checkout@v1
      - name: Download .gradle folder
        uses: actions/download-artifact@v1
        with:
          name: .gradle
      - name: Download build folder
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Download log4k/build folder
        uses: actions/download-artifact@v1
        with:
          name: log4k_build
      - shell: bash
        run: |
          ./scripts/secret decrypt --password ${SECRETS_KEY}
          ./scripts/publish
